In [1]:
import numpy as np
import random
import scipy.stats as sps

In [7]:
a = np.random.sample((3, 3))
b = np.random.sample((3, 3))
print(a)
print()
print(b)

[[0.68051087 0.11844432 0.96438182]
 [0.81208557 0.32319254 0.89395849]
 [0.27128966 0.27103245 0.92906319]]

[[0.19509442 0.21441582 0.86692988]
 [0.14912432 0.51407724 0.39196074]
 [0.09757515 0.31146775 0.86881169]]


In [13]:
def mult(a, b):
    first = a
    second = b
    result = []
    l = len(first[0])
    for i in range(0, l):
        next_list = []
        for j in range(0, l):
            sum = 0
            for z in range(0, l):
                sum+= first[i][z] * second[z][j]
            next_list.append(sum)
        result.append(next_list)
    return result


In [14]:
print(mult(a, b))

[[0.244526505029538, 0.5071756570416883, 1.4742469226957735], [0.2938573666741859, 0.6187091581610626, 1.6073816182795841], [0.18399811222302387, 0.48687362621041474, 1.148604147847183]]


In [15]:
def np_mult(a, b):
    first = a
    second = b
    return first @ second

In [16]:
print(np_mult(a, b))

[[0.24452651 0.50717566 1.47424692]
 [0.29385737 0.61870916 1.60738162]
 [0.18399811 0.48687363 1.14860415]]


In [19]:
a = np.array([[5, 1, -2, 0], [0, 3, 4, 3], [2, 3, 1, 1]])
b = np.array([[1, -3], [2, -2], [3, -1], [0, 0]])
c = a @ b
print(c)

[[  1 -15]
 [ 18 -10]
 [ 11 -13]]


In [29]:
def no_numpy_scalar(v1, v2):
    #param v1, v2: lists of 3 ints
    #YOUR CODE: please do not use numpy
    l = len(v1)
    cummul = 0
    for i in range(l):
        cummul+=v1[i]*v2[i]
    
    result = cummul
    return result

def numpy_scalar (v1, v2):
    #param v1, v2: np.arrays[3]
    #YOUR CODE

    result = v1 @ v2
    return result

In [30]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])
print(numpy_scalar(v1, v2))
print(no_numpy_scalar(v1, v2))

14
14


In [36]:
def diag_2k(a):
    #param a: np.array[size, size]
    #YOUR CODE
    l = len(a)
    sum = 0
    for i in range(l):
        if a[i][i] % 2 == 0:
            sum+= a[i][i]
    result = sum
    return result

In [38]:
a = np.array([[1, 2], [2, 8]])
print(diag_2k(a))

8
