In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), type(a))
print(b)

<class 'numpy.ndarray'> <class 'list'>
[1. 2. 3.]


In [4]:
#set(dir(b)) - set(dir(object))

In [5]:
arr = np.array([1, 2, 3, 4, 5], dtype='int32')
print(arr.nbytes)

20


In [6]:
#np.lookfor('mean value of array')

In [7]:
arr = np.array([[
                [1, 2, 3, 4],
                [1, 2, 3, 4],
                [1, 2, 3, 4]
            ],[
                [1, 2, 3, 4],
                [1, 2, 3, 4],
                [11, 12, 13, 14]
            ]])
print(arr)

[[[ 1  2  3  4]
  [ 1  2  3  4]
  [ 1  2  3  4]]

 [[ 1  2  3  4]
  [ 1  2  3  4]
  [11 12 13 14]]]


In [8]:
print(len(arr))
print(arr.size)
print(arr.ndim)
print(arr.shape)

2
24
3
(2, 3, 4)


In [9]:
arr[1,-1,-1]

14

In [10]:
for i, a in enumerate(arr):
    print(i, a)

0 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
1 [[ 1  2  3  4]
 [ 1  2  3  4]
 [11 12 13 14]]


In [11]:
arr = np.array([2, 3, 5, 7])
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

int32
<class 'numpy.ndarray'>
(4,)
16


In [12]:
a = np.zeros(7)
print(a)
b = np.ones(7, dtype=np.int16)
print(b)
c = np.zeros_like(b)
print(c)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]
[0 0 0 0 0 0 0]


In [13]:
d = np.hstack((a, b))
print(d)

[0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
arr2 = np.hsplit(arr, [3,7,11])
print(arr2)

[array([0, 1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10]), array([11, 12, 13, 14, 15, 16, 17, 18, 19])]


In [16]:
x = np.linspace(-np.pi, np.pi, 100)
np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)

True

In [17]:
b = np.arange(0, 20)
print(b)
b.shape = (2, 10)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [18]:
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [22]:
a = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
print(a)

[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


In [23]:
a = 5*np.ones((5, 5))
print(a)
b = np.eye(5) + 1
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [24]:
print(a*b)

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]]


In [25]:
print(a @ b)

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [26]:
print(a.dot(b))

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [33]:
u = np.linspace(1, 2, 2)
print(u)
v = np.linspace(4, 8, 3)
print(v,"\n")
x, y = np.meshgrid(v, u)
print(x, '\n')
print(y)

[1. 2.]
[4. 6. 8.] 

[[4. 6. 8.]
 [4. 6. 8.]] 

[[1. 1. 1.]
 [2. 2. 2.]]


In [34]:
print(x.reshape(6))

[4. 6. 8. 4. 6. 8.]


In [39]:
is_prime = np.ones(100, dtype=bool)
is_prime[:2] = False

N_max = int(np.sqrt(len(is_prime)))
for i in range(2, N_max):
    is_prime[2*i::i] = False

is_prime

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

In [40]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


In [42]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


In [43]:
x = np.arange(64).reshape(8, 2, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [44]:
np.sum(x)

2016

In [45]:
print(np.sum(x, axis=0))

[[224 232 240 248]
 [256 264 272 280]]


In [46]:
print(np.sum(x, axis=1))

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]]


In [47]:
print(np.sum(x, axis=2))

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]]


определитель

In [48]:
a = np.array([[2, 1], [2, 3]])
np.linalg.det(a)

4.0

нахождение обратной матрицы

In [49]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [50]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [52]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [61]:
t = c.T
print(t)

[[2 6]
 [1 3]]


In [56]:
# np.linalg.inv(c)

решение НЛУ

In [58]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


In [65]:
sum_values = np.sum(np.arange(10**7))
print(sum_values)

-2014260032
